//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YekanPedia.SmsManagement.InfraStructure.AsanakSmsGateway {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://webService.compositeSmsGateway.services.sdp.peykasa.com/", ConfigurationName="AsanakSmsGateway.CompositeSmsGateway")]
    public interface CompositeSmsGateway {
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(baseResult))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        YekanPedia.SmsManagement.InfraStructure.AsanakSmsGateway.getReportByMsgIdResponse getReportByMsgId(YekanPedia.SmsManagement.InfraStructure.AsanakSmsGateway.getReportByMsgId request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<YekanPedia.SmsManagement.InfraStructure.AsanakSmsGateway.getReportByMsgIdResponse> getReportByMsgIdAsync(YekanPedia.SmsManagement.InfraStructure.AsanakSmsGateway.getReportByMsgId request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(baseResult))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        YekanPedia.SmsManagement.InfraStructure.AsanakSmsGateway.getReceivedMsgResponse getReceivedMsg(YekanPedia.SmsManagement.InfraStructure.AsanakSmsGateway.getReceivedMsg request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<YekanPedia.SmsManagement.InfraStructure.AsanakSmsGateway.getReceivedMsgResponse> getReceivedMsgAsync(YekanPedia.SmsManagement.InfraStructure.AsanakSmsGateway.getReceivedMsg request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(baseResult))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        YekanPedia.SmsManagement.InfraStructure.AsanakSmsGateway.getUserCreditResponse getUserCredit(YekanPedia.SmsManagement.InfraStructure.AsanakSmsGateway.getUserCredit request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<YekanPedia.SmsManagement.InfraStructure.AsanakSmsGateway.getUserCreditResponse> getUserCreditAsync(YekanPedia.SmsManagement.InfraStructure.AsanakSmsGateway.getUserCredit request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(baseResult))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        YekanPedia.SmsManagement.InfraStructure.AsanakSmsGateway.sendSmsResponse sendSms(YekanPedia.SmsManagement.InfraStructure.AsanakSmsGateway.sendSms request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<YekanPedia.SmsManagement.InfraStructure.AsanakSmsGateway.sendSmsResponse> sendSmsAsync(YekanPedia.SmsManagement.InfraStructure.AsanakSmsGateway.sendSms request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webService.compositeSmsGateway.services.sdp.peykasa.com/")]
    public partial class userCredential : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string passwordField;
        
        private string usernameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("password");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
                this.RaisePropertyChanged("username");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webService.compositeSmsGateway.services.sdp.peykasa.com/")]
    public partial class receivedMsg : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string bodyField;
        
        private string destinationField;
        
        private int encodingField;
        
        private long idField;
        
        private int partCountField;
        
        private long receivedTimeField;
        
        private string sourceField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string body {
            get {
                return this.bodyField;
            }
            set {
                this.bodyField = value;
                this.RaisePropertyChanged("body");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string destination {
            get {
                return this.destinationField;
            }
            set {
                this.destinationField = value;
                this.RaisePropertyChanged("destination");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int encoding {
            get {
                return this.encodingField;
            }
            set {
                this.encodingField = value;
                this.RaisePropertyChanged("encoding");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public long id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int partCount {
            get {
                return this.partCountField;
            }
            set {
                this.partCountField = value;
                this.RaisePropertyChanged("partCount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public long receivedTime {
            get {
                return this.receivedTimeField;
            }
            set {
                this.receivedTimeField = value;
                this.RaisePropertyChanged("receivedTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string source {
            get {
                return this.sourceField;
            }
            set {
                this.sourceField = value;
                this.RaisePropertyChanged("source");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webService.compositeSmsGateway.services.sdp.peykasa.com/")]
    public partial class reportItem : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long deliveryDateField;
        
        private string destinationField;
        
        private long msgIdField;
        
        private string sourceField;
        
        private int statusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public long deliveryDate {
            get {
                return this.deliveryDateField;
            }
            set {
                this.deliveryDateField = value;
                this.RaisePropertyChanged("deliveryDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string destination {
            get {
                return this.destinationField;
            }
            set {
                this.destinationField = value;
                this.RaisePropertyChanged("destination");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public long msgId {
            get {
                return this.msgIdField;
            }
            set {
                this.msgIdField = value;
                this.RaisePropertyChanged("msgId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string source {
            get {
                return this.sourceField;
            }
            set {
                this.sourceField = value;
                this.RaisePropertyChanged("source");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("status");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(sendSmsResult))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(userCreditResult))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(getReceivedMsgResult))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(getReportByMsgIdResult))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webService.compositeSmsGateway.services.sdp.peykasa.com/")]
    public abstract partial class baseResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string errorMsgField;
        
        private int statusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string errorMsg {
            get {
                return this.errorMsgField;
            }
            set {
                this.errorMsgField = value;
                this.RaisePropertyChanged("errorMsg");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("status");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webService.compositeSmsGateway.services.sdp.peykasa.com/")]
    public partial class sendSmsResult : baseResult {
        
        private System.Nullable<long>[] msgIdArrayField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("msgIdArray", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public System.Nullable<long>[] msgIdArray {
            get {
                return this.msgIdArrayField;
            }
            set {
                this.msgIdArrayField = value;
                this.RaisePropertyChanged("msgIdArray");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webService.compositeSmsGateway.services.sdp.peykasa.com/")]
    public partial class userCreditResult : baseResult {
        
        private int creditField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int credit {
            get {
                return this.creditField;
            }
            set {
                this.creditField = value;
                this.RaisePropertyChanged("credit");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webService.compositeSmsGateway.services.sdp.peykasa.com/")]
    public partial class getReceivedMsgResult : baseResult {
        
        private receivedMsg[] receivedMegsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("receivedMegs", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public receivedMsg[] receivedMegs {
            get {
                return this.receivedMegsField;
            }
            set {
                this.receivedMegsField = value;
                this.RaisePropertyChanged("receivedMegs");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webService.compositeSmsGateway.services.sdp.peykasa.com/")]
    public partial class getReportByMsgIdResult : baseResult {
        
        private reportItem[] reportItemsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("reportItems", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public reportItem[] reportItems {
            get {
                return this.reportItemsField;
            }
            set {
                this.reportItemsField = value;
                this.RaisePropertyChanged("reportItems");
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getReportByMsgId", WrapperNamespace="http://webService.compositeSmsGateway.services.sdp.peykasa.com/", IsWrapped=true)]
    public partial class getReportByMsgId {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webService.compositeSmsGateway.services.sdp.peykasa.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public YekanPedia.SmsManagement.InfraStructure.AsanakSmsGateway.userCredential userCredential;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webService.compositeSmsGateway.services.sdp.peykasa.com/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute("msgIds", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long[] msgIds;
        
        public getReportByMsgId() {
        }
        
        public getReportByMsgId(YekanPedia.SmsManagement.InfraStructure.AsanakSmsGateway.userCredential userCredential, long[] msgIds) {
            this.userCredential = userCredential;
            this.msgIds = msgIds;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getReportByMsgIdResponse", WrapperNamespace="http://webService.compositeSmsGateway.services.sdp.peykasa.com/", IsWrapped=true)]
    public partial class getReportByMsgIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webService.compositeSmsGateway.services.sdp.peykasa.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public YekanPedia.SmsManagement.InfraStructure.AsanakSmsGateway.getReportByMsgIdResult @return;
        
        public getReportByMsgIdResponse() {
        }
        
        public getReportByMsgIdResponse(YekanPedia.SmsManagement.InfraStructure.AsanakSmsGateway.getReportByMsgIdResult @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getReceivedMsg", WrapperNamespace="http://webService.compositeSmsGateway.services.sdp.peykasa.com/", IsWrapped=true)]
    public partial class getReceivedMsg {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webService.compositeSmsGateway.services.sdp.peykasa.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public YekanPedia.SmsManagement.InfraStructure.AsanakSmsGateway.userCredential userCredential;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webService.compositeSmsGateway.services.sdp.peykasa.com/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute("destAddresses", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string[] destAddresses;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webService.compositeSmsGateway.services.sdp.peykasa.com/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long fromTime;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webService.compositeSmsGateway.services.sdp.peykasa.com/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int maxReturnedMsg;
        
        public getReceivedMsg() {
        }
        
        public getReceivedMsg(YekanPedia.SmsManagement.InfraStructure.AsanakSmsGateway.userCredential userCredential, string[] destAddresses, long fromTime, int maxReturnedMsg) {
            this.userCredential = userCredential;
            this.destAddresses = destAddresses;
            this.fromTime = fromTime;
            this.maxReturnedMsg = maxReturnedMsg;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getReceivedMsgResponse", WrapperNamespace="http://webService.compositeSmsGateway.services.sdp.peykasa.com/", IsWrapped=true)]
    public partial class getReceivedMsgResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webService.compositeSmsGateway.services.sdp.peykasa.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public YekanPedia.SmsManagement.InfraStructure.AsanakSmsGateway.getReceivedMsgResult @return;
        
        public getReceivedMsgResponse() {
        }
        
        public getReceivedMsgResponse(YekanPedia.SmsManagement.InfraStructure.AsanakSmsGateway.getReceivedMsgResult @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getUserCredit", WrapperNamespace="http://webService.compositeSmsGateway.services.sdp.peykasa.com/", IsWrapped=true)]
    public partial class getUserCredit {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webService.compositeSmsGateway.services.sdp.peykasa.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public YekanPedia.SmsManagement.InfraStructure.AsanakSmsGateway.userCredential userCredential;
        
        public getUserCredit() {
        }
        
        public getUserCredit(YekanPedia.SmsManagement.InfraStructure.AsanakSmsGateway.userCredential userCredential) {
            this.userCredential = userCredential;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getUserCreditResponse", WrapperNamespace="http://webService.compositeSmsGateway.services.sdp.peykasa.com/", IsWrapped=true)]
    public partial class getUserCreditResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webService.compositeSmsGateway.services.sdp.peykasa.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public YekanPedia.SmsManagement.InfraStructure.AsanakSmsGateway.userCreditResult @return;
        
        public getUserCreditResponse() {
        }
        
        public getUserCreditResponse(YekanPedia.SmsManagement.InfraStructure.AsanakSmsGateway.userCreditResult @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sendSms", WrapperNamespace="http://webService.compositeSmsGateway.services.sdp.peykasa.com/", IsWrapped=true)]
    public partial class sendSms {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webService.compositeSmsGateway.services.sdp.peykasa.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public YekanPedia.SmsManagement.InfraStructure.AsanakSmsGateway.userCredential userCredential;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webService.compositeSmsGateway.services.sdp.peykasa.com/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute("srcAddresses", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string[] srcAddresses;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webService.compositeSmsGateway.services.sdp.peykasa.com/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute("destAddresses", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string[] destAddresses;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webService.compositeSmsGateway.services.sdp.peykasa.com/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute("msgBody", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string[] msgBody;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webService.compositeSmsGateway.services.sdp.peykasa.com/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute("msgEncoding", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int[] msgEncoding;
        
        public sendSms() {
        }
        
        public sendSms(YekanPedia.SmsManagement.InfraStructure.AsanakSmsGateway.userCredential userCredential, string[] srcAddresses, string[] destAddresses, string[] msgBody, int[] msgEncoding) {
            this.userCredential = userCredential;
            this.srcAddresses = srcAddresses;
            this.destAddresses = destAddresses;
            this.msgBody = msgBody;
            this.msgEncoding = msgEncoding;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sendSmsResponse", WrapperNamespace="http://webService.compositeSmsGateway.services.sdp.peykasa.com/", IsWrapped=true)]
    public partial class sendSmsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webService.compositeSmsGateway.services.sdp.peykasa.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public YekanPedia.SmsManagement.InfraStructure.AsanakSmsGateway.sendSmsResult @return;
        
        public sendSmsResponse() {
        }
        
        public sendSmsResponse(YekanPedia.SmsManagement.InfraStructure.AsanakSmsGateway.sendSmsResult @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CompositeSmsGatewayChannel : YekanPedia.SmsManagement.InfraStructure.AsanakSmsGateway.CompositeSmsGateway, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CompositeSmsGatewayClient : System.ServiceModel.ClientBase<YekanPedia.SmsManagement.InfraStructure.AsanakSmsGateway.CompositeSmsGateway>, YekanPedia.SmsManagement.InfraStructure.AsanakSmsGateway.CompositeSmsGateway {
        
        public CompositeSmsGatewayClient() {
        }
        
        public CompositeSmsGatewayClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CompositeSmsGatewayClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CompositeSmsGatewayClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CompositeSmsGatewayClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        YekanPedia.SmsManagement.InfraStructure.AsanakSmsGateway.getReportByMsgIdResponse YekanPedia.SmsManagement.InfraStructure.AsanakSmsGateway.CompositeSmsGateway.getReportByMsgId(YekanPedia.SmsManagement.InfraStructure.AsanakSmsGateway.getReportByMsgId request) {
            return base.Channel.getReportByMsgId(request);
        }
        
        public YekanPedia.SmsManagement.InfraStructure.AsanakSmsGateway.getReportByMsgIdResult getReportByMsgId(YekanPedia.SmsManagement.InfraStructure.AsanakSmsGateway.userCredential userCredential, long[] msgIds) {
            YekanPedia.SmsManagement.InfraStructure.AsanakSmsGateway.getReportByMsgId inValue = new YekanPedia.SmsManagement.InfraStructure.AsanakSmsGateway.getReportByMsgId();
            inValue.userCredential = userCredential;
            inValue.msgIds = msgIds;
            YekanPedia.SmsManagement.InfraStructure.AsanakSmsGateway.getReportByMsgIdResponse retVal = ((YekanPedia.SmsManagement.InfraStructure.AsanakSmsGateway.CompositeSmsGateway)(this)).getReportByMsgId(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<YekanPedia.SmsManagement.InfraStructure.AsanakSmsGateway.getReportByMsgIdResponse> YekanPedia.SmsManagement.InfraStructure.AsanakSmsGateway.CompositeSmsGateway.getReportByMsgIdAsync(YekanPedia.SmsManagement.InfraStructure.AsanakSmsGateway.getReportByMsgId request) {
            return base.Channel.getReportByMsgIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<YekanPedia.SmsManagement.InfraStructure.AsanakSmsGateway.getReportByMsgIdResponse> getReportByMsgIdAsync(YekanPedia.SmsManagement.InfraStructure.AsanakSmsGateway.userCredential userCredential, long[] msgIds) {
            YekanPedia.SmsManagement.InfraStructure.AsanakSmsGateway.getReportByMsgId inValue = new YekanPedia.SmsManagement.InfraStructure.AsanakSmsGateway.getReportByMsgId();
            inValue.userCredential = userCredential;
            inValue.msgIds = msgIds;
            return ((YekanPedia.SmsManagement.InfraStructure.AsanakSmsGateway.CompositeSmsGateway)(this)).getReportByMsgIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        YekanPedia.SmsManagement.InfraStructure.AsanakSmsGateway.getReceivedMsgResponse YekanPedia.SmsManagement.InfraStructure.AsanakSmsGateway.CompositeSmsGateway.getReceivedMsg(YekanPedia.SmsManagement.InfraStructure.AsanakSmsGateway.getReceivedMsg request) {
            return base.Channel.getReceivedMsg(request);
        }
        
        public YekanPedia.SmsManagement.InfraStructure.AsanakSmsGateway.getReceivedMsgResult getReceivedMsg(YekanPedia.SmsManagement.InfraStructure.AsanakSmsGateway.userCredential userCredential, string[] destAddresses, long fromTime, int maxReturnedMsg) {
            YekanPedia.SmsManagement.InfraStructure.AsanakSmsGateway.getReceivedMsg inValue = new YekanPedia.SmsManagement.InfraStructure.AsanakSmsGateway.getReceivedMsg();
            inValue.userCredential = userCredential;
            inValue.destAddresses = destAddresses;
            inValue.fromTime = fromTime;
            inValue.maxReturnedMsg = maxReturnedMsg;
            YekanPedia.SmsManagement.InfraStructure.AsanakSmsGateway.getReceivedMsgResponse retVal = ((YekanPedia.SmsManagement.InfraStructure.AsanakSmsGateway.CompositeSmsGateway)(this)).getReceivedMsg(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<YekanPedia.SmsManagement.InfraStructure.AsanakSmsGateway.getReceivedMsgResponse> YekanPedia.SmsManagement.InfraStructure.AsanakSmsGateway.CompositeSmsGateway.getReceivedMsgAsync(YekanPedia.SmsManagement.InfraStructure.AsanakSmsGateway.getReceivedMsg request) {
            return base.Channel.getReceivedMsgAsync(request);
        }
        
        public System.Threading.Tasks.Task<YekanPedia.SmsManagement.InfraStructure.AsanakSmsGateway.getReceivedMsgResponse> getReceivedMsgAsync(YekanPedia.SmsManagement.InfraStructure.AsanakSmsGateway.userCredential userCredential, string[] destAddresses, long fromTime, int maxReturnedMsg) {
            YekanPedia.SmsManagement.InfraStructure.AsanakSmsGateway.getReceivedMsg inValue = new YekanPedia.SmsManagement.InfraStructure.AsanakSmsGateway.getReceivedMsg();
            inValue.userCredential = userCredential;
            inValue.destAddresses = destAddresses;
            inValue.fromTime = fromTime;
            inValue.maxReturnedMsg = maxReturnedMsg;
            return ((YekanPedia.SmsManagement.InfraStructure.AsanakSmsGateway.CompositeSmsGateway)(this)).getReceivedMsgAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        YekanPedia.SmsManagement.InfraStructure.AsanakSmsGateway.getUserCreditResponse YekanPedia.SmsManagement.InfraStructure.AsanakSmsGateway.CompositeSmsGateway.getUserCredit(YekanPedia.SmsManagement.InfraStructure.AsanakSmsGateway.getUserCredit request) {
            return base.Channel.getUserCredit(request);
        }
        
        public YekanPedia.SmsManagement.InfraStructure.AsanakSmsGateway.userCreditResult getUserCredit(YekanPedia.SmsManagement.InfraStructure.AsanakSmsGateway.userCredential userCredential) {
            YekanPedia.SmsManagement.InfraStructure.AsanakSmsGateway.getUserCredit inValue = new YekanPedia.SmsManagement.InfraStructure.AsanakSmsGateway.getUserCredit();
            inValue.userCredential = userCredential;
            YekanPedia.SmsManagement.InfraStructure.AsanakSmsGateway.getUserCreditResponse retVal = ((YekanPedia.SmsManagement.InfraStructure.AsanakSmsGateway.CompositeSmsGateway)(this)).getUserCredit(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<YekanPedia.SmsManagement.InfraStructure.AsanakSmsGateway.getUserCreditResponse> YekanPedia.SmsManagement.InfraStructure.AsanakSmsGateway.CompositeSmsGateway.getUserCreditAsync(YekanPedia.SmsManagement.InfraStructure.AsanakSmsGateway.getUserCredit request) {
            return base.Channel.getUserCreditAsync(request);
        }
        
        public System.Threading.Tasks.Task<YekanPedia.SmsManagement.InfraStructure.AsanakSmsGateway.getUserCreditResponse> getUserCreditAsync(YekanPedia.SmsManagement.InfraStructure.AsanakSmsGateway.userCredential userCredential) {
            YekanPedia.SmsManagement.InfraStructure.AsanakSmsGateway.getUserCredit inValue = new YekanPedia.SmsManagement.InfraStructure.AsanakSmsGateway.getUserCredit();
            inValue.userCredential = userCredential;
            return ((YekanPedia.SmsManagement.InfraStructure.AsanakSmsGateway.CompositeSmsGateway)(this)).getUserCreditAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        YekanPedia.SmsManagement.InfraStructure.AsanakSmsGateway.sendSmsResponse YekanPedia.SmsManagement.InfraStructure.AsanakSmsGateway.CompositeSmsGateway.sendSms(YekanPedia.SmsManagement.InfraStructure.AsanakSmsGateway.sendSms request) {
            return base.Channel.sendSms(request);
        }
        
        public YekanPedia.SmsManagement.InfraStructure.AsanakSmsGateway.sendSmsResult sendSms(YekanPedia.SmsManagement.InfraStructure.AsanakSmsGateway.userCredential userCredential, string[] srcAddresses, string[] destAddresses, string[] msgBody, int[] msgEncoding) {
            YekanPedia.SmsManagement.InfraStructure.AsanakSmsGateway.sendSms inValue = new YekanPedia.SmsManagement.InfraStructure.AsanakSmsGateway.sendSms();
            inValue.userCredential = userCredential;
            inValue.srcAddresses = srcAddresses;
            inValue.destAddresses = destAddresses;
            inValue.msgBody = msgBody;
            inValue.msgEncoding = msgEncoding;
            YekanPedia.SmsManagement.InfraStructure.AsanakSmsGateway.sendSmsResponse retVal = ((YekanPedia.SmsManagement.InfraStructure.AsanakSmsGateway.CompositeSmsGateway)(this)).sendSms(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<YekanPedia.SmsManagement.InfraStructure.AsanakSmsGateway.sendSmsResponse> YekanPedia.SmsManagement.InfraStructure.AsanakSmsGateway.CompositeSmsGateway.sendSmsAsync(YekanPedia.SmsManagement.InfraStructure.AsanakSmsGateway.sendSms request) {
            return base.Channel.sendSmsAsync(request);
        }
        
        public System.Threading.Tasks.Task<YekanPedia.SmsManagement.InfraStructure.AsanakSmsGateway.sendSmsResponse> sendSmsAsync(YekanPedia.SmsManagement.InfraStructure.AsanakSmsGateway.userCredential userCredential, string[] srcAddresses, string[] destAddresses, string[] msgBody, int[] msgEncoding) {
            YekanPedia.SmsManagement.InfraStructure.AsanakSmsGateway.sendSms inValue = new YekanPedia.SmsManagement.InfraStructure.AsanakSmsGateway.sendSms();
            inValue.userCredential = userCredential;
            inValue.srcAddresses = srcAddresses;
            inValue.destAddresses = destAddresses;
            inValue.msgBody = msgBody;
            inValue.msgEncoding = msgEncoding;
            return ((YekanPedia.SmsManagement.InfraStructure.AsanakSmsGateway.CompositeSmsGateway)(this)).sendSmsAsync(inValue);
        }
    }
}
